source 'https://rubygems.org'

gem 'kramdown', '~> 2.5'
gem 'kramdown-parser-gfm', '~> 1.1'
gem 'rubypants'
gem 'rack', '>= 1.0'
gem 'rackup'
gem 'rack-session'
gem 'webrick'
gem 'rouge', '~> 4.0'
gem 'kontrol', '>= 0.3.1'
gem 'ruby_llm', '~> 1.9'
gem 'rspec', '~> 3.0'
gem 'rake'
gem 'rdoc'
gem 'rack-test'
gem 'rexml'
